/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativetest */

#ifndef _Included_nativetest
#define _Included_nativetest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativetest
 * Method:    startSimulator
 * Signature: (S[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_nativetest_startSimulator
  (JNIEnv *, jobject, jshort, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
